### ISSUE TITLE
Any Idea What is the problem?

### ISSUE THREAD

**Issue by BashirKhankan** [matthewhartman/urban-dictionary-lookup#3]
udefine unix
file:///usr/local/lib/node_modules/urban-dictionary-lookup/index.js:23
const response = await fetch(`https://www.urbandictionary.com/define.php?term=${args[0]}`);
                 ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)

**Comment by matthewhartman** [comment]
Hey @BashirKhankan,

Could you please run the commands below and report back the versions you are using.

```bash
node -v
npm -v
```
